<a href="https://colab.research.google.com/github/SSUMINIs/mulcam34/blob/main/numpy_240103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.26.3


In [ ]:
# !pip install numpy #바로 설치 가능

In [ ]:
num1 = [1,2,3,4]
num2 = [3,4,5,6]
num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [ ]:
arr1 = np.array(num1)
arr2 = np.array(num2)
arr1 + arr2

array([ 4,  6,  8, 10])

In [ ]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
a1.dtype #python int #numpy int8, int16, int32, int64 ->메모리관리와 연관

dtype('int32')

In [ ]:
np.array([0.5,2,0.01,8]).dtype

dtype('float64')

# Numpy 배열생성
- 1차원, 2차원, 3차원.. 배열생성

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(10) #1차원 배열을 2차원 또는 3차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
b1 = np.arange(12).reshape(2,2,3)
b1.shape

(2, 2, 3)

In [ ]:
# 범위의 시작과 끝 정하기 배열 생성

In [ ]:
np.linspace(0,10,5) # (시작, 끝, 원소의 개수[균등]) 0과 10사이에 숫자가 5개 나오게

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#단위 행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr_I.shape

(3, 3)

In [ ]:
np.array(['1.5','0.62'])

array(['1.5', '0.62'], dtype='<U4')

In [ ]:
#astype() #판다스에서 사용가능
arr = np.array(['1.5','0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

In [ ]:
np.array(['1.5','0.62'],dtype=float)

array([1.5 , 0.62])

In [ ]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_f1 = num_f1.astype(int)
num_f1
#값이 유실됨. 일치시키고 싶으면 int로 바꾸는거보다, float로 변경

array([10, 21,  0,  4,  5])

In [ ]:
#난수 무작위로 숫자를 추출한다
np.random.rand(2,3) #0~1사이의 실수 난수를 갖음(배열의 크기)

array([[0.82484637, 0.81334983, 0.56091005],
       [0.91856595, 0.17480215, 0.39500014]])

In [ ]:
np.random.randint(1,100,10) #(처음, 끝범위,원소개수)

array([96,  8, 28,  4, 27, 63, 17, 80, 50, 10])

In [ ]:
#로또 번호 생성기
np.random.randint(1,50,6)

array([20, 46,  7,  5, 31, 22])

In [ ]:
import random
lotto = []
num = np.random.randint(1,45)

for i in range(6):
    while num in lotto:
        num = np.random.randint(1,45)
    lotto.append(num)
print(lotto)

[27, 37, 2, 1, 23, 12]


In [ ]:
import random
l_num = list(range(1,46))
random.sample(l_num, 6)

[21, 8, 7, 17, 37, 23]

In [ ]:
np.random.choice(list(range(1,46)), 6, replace=False)

array([23,  6, 28, 18,  8, 27])

In [ ]:
np.random.randint(1,2,6)

array([1, 1, 1, 1, 1, 1])

In [ ]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



배열의 연산

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


비교연산

In [ ]:
arr1 > 20

array([False, False,  True,  True])

In [ ]:
## 통계 연산
- numpy, 합, 평균, 표준 편차, 분산, 최솟값, 최댓값, 누적합, 누적 곱 메서드가 존재한다.
    + 합, 평균, 표준 편차, 분산, 최솟값, 최댓값 =>기술통계량 (descriptive statistics) : 현재 데이터 상태를 표현(=묘사, Describe)한다.
- 통계 : 평균이 전부다!(Mean is Everything)
    + 모수 통계
    + 비모수 통계
    + 베이지안 통계

In [ ]:
arr3 = np.arange(5)
print(arr3)
print(arr3.sum())
print(arr3.mean())
print(arr3.std())
print(arr3.var())

[0 1 2 3 4]
10
2.0
1.4142135623730951
2.0


In [ ]:
## 누적합과 누적곱
- cumsum() : 누적합, cumprod() : 누적곱

In [ ]:
arr4 = np.arange(1,5)
print(arr4)
print(arr4.cumsum())
print(arr4.cumprod())

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [ ]:
## 행렬연산
- 선형대수(Linear Algebra)를 위한 2차원 배열 연산도 지원

In [ ]:
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,0,1]).reshape(2,2)

A.dot(B) #=np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [ ]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
# 배열의 인덱싱과 슬라이싱
- string, list, tuple과 동일한 방법으로 접근

In [ ]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
#리스트 통해서 추출
a1[[0,2,4]]

array([ 0, 20, 40])

In [ ]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1,0] = 45
a2

array([[10, 20, 30],
       [45, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[0] = np.array([1,2,3]) #a2[0] = [1,2,3]도 가능 but 배열=리스트니까 정석은 아님. 자료형태 맞춰주는게 좋음
a2

array([[ 1,  2,  3],
       [45, 50, 60],
       [70, 80, 95]])

In [ ]:
- 2차원 배열의 행과 열 위치 지정해서 원소 추출

In [ ]:
a2[[0,2],[0,1]] #[[행1,행2],[열1,열2]]

array([ 1, 80])

In [ ]:
## 배열 조건문
- pandas 문법과 유사하다

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
## 배열의 슬라이싱
b1 = np.array([0,1,2,3,4,5])
b1[1:4]

array([1, 2, 3])

In [ ]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [ ]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [ ]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3,1:3] #= b2[1:,1:]

array([[50, 60],
       [80, 90]])

In [ ]:
b2[1][1:]

array([50, 60])

In [ ]:
## numpy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.where(arr < 5, arr, arr*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
cond_list = [arr>5,arr <2]
choice_list = [arr*2,arr+100]
np.select(cond_list,choice_list,default=arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])